### PR TITLE
Add CommandLineParser Library to handle arguments on the command line.

### LINKED ISSUE #2: Support parameters to the SqlTzLoader
- We currently populate the Intervals table for 5 years in the future.
- The connection string is pulled from the config file.

Both of these should be things that can be passed in on the command line arguments.

### PR DESCRIPTION
**Pull request by rykerwilliams**
```
CommandLineParser v1.9.71. Resolves #2 
```

### CODE REVIEW

**Comment by mattjohnsonpint** [comment]
On initial review, it looks good!  I'll look closer this weekend and merge.

Thanks!

**Comment by rykerwilliams** [comment]
Thank you for the great library! If you accept this, then adding in new arguments in the command line should be fairly easy moving forward.

I think that keeping a 1 to 1 relationship between settings in the App.config and command line arguments is a good plan? This way, any setting that can be defined via command line can be defined via config file also.

In the future, we could allow the App.Config file itself to be an argument? Default could be to look in the executing directory.

**Comment by rykerwilliams** [comment]
Just wanted to follow up on this PR and see if you had a chance to review it? Thanks!

**Comment by mattjohnsonpint** [comment]
Ok, I took a look.  Could you please make the following enhancements?
- Remove the default option.  I'd rather the App.Config not need to exist.  (delete it)
- Add some help text output for /? or no parameters passed
- Instead of `private static string connectionString;`, do `private static Options _options;`  Use `_options.ConnectionString` where needed.  This will make it easier to add and use more options later if needed.

Thanks!

**Comment by mattjohnsonpint** [comment]
To clarify - I see that `--help` works.  No need to add `/?` - however if no `-c` option is passed, then show the help text as if `--help` was passed.

**Comment by rykerwilliams** [comment]
Updated! By virtue of the required value for the connectionString parameter, typing /? or anything that is not -c/--connectionString does have the desired result of popping up the help. Cheers!

**Pull request merged**
